target 'nasa-images' do
  use_frameworks!

	pod 'SwiftLint'
	pod 'SDWebImage'

  target 'nasa-imagesTests' do
    inherit! :search_paths
	pod 'SnapshotTesting', '~> 1.9.0'
  end

  target 'nasa-imagesUITests' do
    # Pods for testing
  end

end
