# Uncomment the next line to define a global platform for your project


target 'nasa-images' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nasa-images
pod 'SwiftLint'

  target 'nasa-imagesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nasa-imagesUITests' do
    # Pods for testing
  end

end
